version: "3.9"

services:
  app:
    image: sriramk16/vprofile:app
    ports:
      - "8080:8080"

    deploy:
      replicas: 2

      resources:
        limits:
          cpus: "0.35"
          memory: 356M

    networks:
      - appnet
    volumes: 
      - appvol:/usr/local/tomcat
     
  db:
    image: sriramk16/vprofile:db
    ports:
     - "3306:3306"
    
    deploy:
      replicas: 1     

    secrets:
      - db_pass

    networks:
      - appnet
    volumes:
      - dbvol:/var/lib/mysql


networks:
  appnet:
    driver: overlay

volumes:
  appvol:
  dbvol:

secrets:
  db_pass:
    file: ./mariadb_root_password.txt
    external: true
