#Replicas
frontend: 1
backend: 1

#Images
fimage:
  repository: sriramk16/vprofile
  pullPolicy: IfNotPresent
  tag: "app"
dimage:
  repository: sriramk16/personahub
  pullPolicy: IfNotPresent
  tag: "db"
imagePullSecrets: []

#lables
flabels:
  app: frontendapp
  env: dev
dlabels:
  app: backenddb
  env: dev
namespace: personahubdev

#contnames
fcontname:
  name: appcont
dcontname:
  name: dbcont

#resources
resources:
  requests:
    cpu: "0.25m"
    memory: "400Mi"
  limits:
    cpu: "0.35m"
    memory: "450Mi"

#volumes
dvolumeMounts:
  - name: dbvol
    mountPath: /var/lib/mysql
dvolumes:
  - name: dbvol
    hostPath:
      path: /opt/data

secret:
  dbpass: ZGIxMnBhc3MzNAo=

#services
dservice:
  type: ClusterIP
  port: 3306
  targetPort: 3306
fservice:
  type: LoadBalancer
  loadBalancerEnabled: true
fports:
   port: 8080
   nodePort: 30000
   targetPort: 8080

#midtier
mreplicas: 1
mlabels:
  app: mq
  env: dev
mcontname:
  name: mqcont
mimage:
  repository: rabbitmq
  pullPolicy: IfNotPresent
  tag: "4.2"

mports:
  type: ClusterIP
  port: 15672
  targetPort: 15672
mservice:
  name: vpromq01
  type: ClusterIP

#memcached
mcreplicas: 1
mclabels:
  app: mc
mccontname:
  name: mccont
mcimage:
  repository: memcached
  pullPolicy: IfNotPresent
  tag: "1.6"
mcports:
  type: ClusterIP
  port: 11211
  targetPort: 11211
mcservice:
  name: vprocache01
  type: ClusterIP
