#Replicas
frontend: 2
backend: 1

#Images
fimage:
  repository: sriramk16/vprofile
  pullPolicy: IfNotPresent
  tag: "app"
dimage:
  repository: sriramk16/personahub
  pullPolicy: IfNotPresent
  tag: "db"
imagePullSecrets: []

#lables
flabels:
  app: frontendapp
  env: dev
dlabels:
  app: backenddb
  env: dev
namespace: personahubdev

#contnames
fcontname:
  name: appcont
dcontname:
  name: dbcont

#resources
resources:
  requests:
    cpu: "0.25m"
    memory: "250Mi"
  limits:
    cpu: "0.35m"
    memory: "350Mi"

#volumes
dvolumeMounts:
  - name: dbvol
    mountPath: /var/lib/mysql
dvolumes:
  - name: dbvol
    hostPath:
      path: /opt/data

secret:
  dbpass: ZGIxMnBhc3MzNAo=

#services
dservice:
  type: ClusterIP
  port: 3306
  targetPort: 3306
fservice:
  type: NodePort
  nodePortEnabled: true
fports:
  - port: 8080
    nodePort: 30000
    targetPort: 8080
