---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Values.namespace }}
spec:
  {{- if $.Values.fservice.loadBalancerEnabled }}
  type: {{ .Values.fservice.type }}
  {{- end }}
  selector:
    app: {{ .Values.flabels.app }}
  ports:
    - port: {{ .Values.fports.port }}
      nodePort: {{ .Values.fports.nodePort }}
      targetPort: {{ .Values.fports.targetPort }}
