---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
spec:
  type: {{ .Values.fservice.type }}
  selector:
    app: {{ .Values.flabels.app }}
  ports:
{{- range.Values.fports }}
    - port: {{ .port }}
      nodePort: {{ .nodePort }}
      targetPort: {{ .targetPort }}
{{- end }}
