---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.dservice.type }}
  selector:
    app: {{ .Values.dlabels.app }}
  ports:
    - port: {{ .Values.dservice.port }}
      targetPort: {{ .Values.dservice.targetPort }}
