apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend }}
  selector:
    matchLabels:
      app: {{ .Values.flabels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.flabels.app }}
    spec:
      containers:
       - name: {{ .Values.fcontname.name }}
         image: {{ .Values.fimage.repository }}:{{ .Values.fimage.tag }}
         ports:
           - containerPort: {{ .Values.fports.targetPort }}

         resources:
{{- toYaml .Values.resources| nindent 10 }}
