apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mservice.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.mservice.type }}
  selector:
    app: {{ .Values.mlabels.app }}
  ports:
    - port: {{ .Values.mports.port }}
      targetPort: {{ .Values.mports.targetPort }}
