apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend }}
  selector:
    matchLabels:
      app: {{ .Values.dlabels.db }}
  template:
    metadata:
      labels:
        app: {{ .Values.dlabels.db }}
    spec:
      containers:
       - name: {{ .Values.dcontname.name }}
         image: {{ .Values.dimage.repository }}:{{ .Values.dimage.tag }}
         env:
           - name: MYSQL_ROOT_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: {{ .Release.Name }}-db
                 key: rootpass
                      
         ports:
           - containerPort: {{ .Values.dservice.targetPort }}
         volumeMounts:        
{{- toYaml .Values.dvolumeMounts | nindent 10 }}
         resources:
{{- toYaml .Values.resources | nindent 10 }}
      volumes:
{{- toYaml .Values.dvolumes | nindent 8 }}
